[main]

[[main.block]]
format = "html"
content_file = "input/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/releases/head.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/navbar.html"

[[main.block]]
format = "html"
content_file = "input/pages/releases/releases.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/footer.html"
