[main]

[[main.block]]
format = "html"
content_file = "input/global/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/downloads/head.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/navbar.html"

[[main.block]]
format = "html"
content_file = "input/pages/downloads/downloads.html"

[[main.block]]
format = "html"
content_file = "input/global/elements/footer.html"
