[main]

[[main.block]]
from_str = "config/global/elements/head.html"
style = "html"

[[main.block]]
from_str = "config/pages/downloads/head.html"
style = "html"

[[main.block]]
from_str = "config/global/elements/navbar.html"
style = "html"

[[main.block]]
from_str = "config/pages/downloads/downloads.html"
style = "html"

[[main.block]]
from_str = "config/global/elements/footer.html"
style = "html"
